version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust

  nuxtapp:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres