version: '3.8'
services:
  nuxtapp:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - src/.env

  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - src/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nuxt-bd 
