version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # POSTGRES_DB: mydb
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: randompassword

  nuxtapp:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres